name: CD with Docker for FastAPI

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REPO }}/gguro-llm:latest
          # GitHub Actions의 캐시 사용
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ secrets.ENV }}" > .env
            sudo docker pull ${{ secrets.DOCKER_REPO }}/gguro-llm:latest
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f