name: CD with Docker for FastAPI

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build and push Docker image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/reviewit .
          docker push ${{ secrets.DOCKER_REPO }}/reviewit

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ secrets.ENV }}" > .env
            sudo docker pull ${{ secrets.DOCKER_REPO }}/reviewit 
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f